./configure --prefix=/usr --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu \
  --extra-version=ultra-clean-pi4-vulkan-headless --arch=aarch64 --cpu=cortex-a72 \
  --extra-cflags='-mcpu=cortex-a72 -O3 -pipe -ftree-vectorize -flto' \
  --extra-ldflags='-latomic -Wl,-O1,--as-needed -flto' \
  --extra-libs='-ldrm -ludev -lvulkan -lstdc++' \
  --enable-shared --disable-static --enable-gpl --enable-nonfree --enable-lto \
  --enable-ffmpeg --enable-ffprobe --disable-ffplay --enable-openssl \
  --enable-libjack --enable-libpulse --enable-alsa --enable-libsoxr --enable-libplacebo \
  --enable-libshaderc --enable-vulkan --enable-libdrm --enable-libudev \
  --enable-sand --enable-v4l2-m2m --enable-v4l2-request --enable-libass \
  --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-vout-drm \
  --disable-sdl2 --disable-opengl --disable-vout-egl --disable-gbm --disable-epoxy \
  --disable-xlib --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-libxcb-shape \
  --disable-libx264 --disable-libx265 --disable-vdpau --disable-vaapi --disable-dxva2 --disable-d3d11va --disable-videotoolbox \
  --disable-audiotoolbox --disable-amf --disable-libmfx --disable-cuda --disable-cuda-llvm \
  --disable-cuvid --disable-nvenc --disable-nvdec --disable-libnpp --disable-ffnvcodec \
  --disable-omx --disable-omx-rpi --disable-mmal \
  --disable-doc --disable-debug --disable-protocol=gopher,mmsh,mmst \
  --disable-decoder=adpcm_g722,adpcm_g726,adpcm_g726le,g723_1,g729,gsm,gsm_ms,comfort_noise,libgsm,libgsm_ms \
  --disable-encoder=gsm,gsm_ms,libgsm,libgsm_ms,g723_1,g726 \
  --disable-decoder=interplay_video,vmdvideo,tiertexseqvideo,cinepak,msvideo1,msrle,idcin,vmnc,cpia,smush,xan_wc3,xan_wc4,ws_snd1,derf_dp,qcelp,crystalhd \
  --disable-manpages --disable-htmlpages --disable-txtpages --disable-podpages \
  --enable-stripping --enable-hardcoded-tables --disable-libvpx
