./configure --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf \
  --extra-version=ultra-clean-pi3-egl-sdl2 --arch=armv7l --target-os=linux --cpu=cortex-a53 \
  --extra-cflags='-mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -O3 -pipe -ftree-vectorize -flto -Wno-stringop-overflow' \
  --extra-ldflags='-latomic -Wl,-O1,--as-needed -flto' \
  --extra-libs='-lgbm -ldrm -lepoxy -lEGL -lGLESv2 -ludev -lvulkan -lSDL2 -lstdc++' \
  --enable-shared --disable-static --enable-gpl --enable-nonfree --enable-lto \
  --enable-ffmpeg --enable-ffprobe --enable-ffplay --enable-openssl \
  --enable-libjack --enable-libpulse --enable-alsa --enable-libsoxr \
  --enable-libdrm --enable-libudev --enable-v4l2-m2m --enable-libass \
  --enable-libfdk-aac --enable-libmp3lame --enable-libopus \
  --enable-vulkan --enable-opengl --enable-vout-drm --enable-vout-egl --enable-gbm --enable-sdl2 \
  --disable-libplacebo --disable-libshaderc --enable-xlib --disable-libxcb --disable-libxcb-shm \
  --disable-libxcb-xfixes --disable-libxcb-shape --disable-libx264 --disable-libx265 \
  --disable-vdpau --disable-vaapi --disable-dxva2 --disable-d3d11va --disable-videotoolbox \
  --disable-audiotoolbox --disable-amf --disable-libmfx --disable-cuda --disable-cuda-llvm \
  --disable-cuvid --disable-nvenc --disable-nvdec --disable-libnpp --disable-ffnvcodec \
  --disable-omx --disable-omx-rpi --disable-mmal \
  --disable-doc --disable-debug --disable-protocol=gopher,mmsh,mmst \
  --disable-decoder=adpcm_g722,adpcm_g726,adpcm_g726le,g723_1,g729,gsm,gsm_ms,comfort_noise,libgsm,libgsm_ms \
  --disable-encoder=gsm,gsm_ms,libgsm,libgsm_ms,g723_1,g726 \
  --disable-decoder=interplay_video,vmdvideo,tiertexseqvideo,cinepak,msvideo1,msrle,idcin,vmnc,cpia,smush,xan_wc3,xan_wc4,ws_snd1,derf_dp,qcelp,crystalhd \
  --disable-manpages --disable-htmlpages --disable-txtpages --disable-podpages \
  --enable-stripping --enable-hardcoded-tables --disable-libvpx
