#!/bin/bash

PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/local/lib/aarch64-linux-gnu/pkgconfig" \
./configure --prefix=/usr \
--libdir=/usr/lib/aarch64-linux-gnu \
--incdir=/usr/include/aarch64-linux-gnu \
--extra-version=ultra-pi4-c \
--arch=aarch64 --target-os=linux --cpu=cortex-a72 \
--extra-cflags='-I/usr/include/libdrm -I/usr/include/gbm -mcpu=cortex-a72+crypto -O2 -pipe -ftree-vectorize -flto -Wno-stringop-overflow -I/usr/include/vulkan' \
--extra-ldflags='-L/usr/lib/aarch64-linux-gnu -Wl,-O1 -Wl,-rpath,/usr/lib/aarch64-linux-gnu -Wl,--as-needed -flto -lstdc++' \
--extra-libs='-lpthread -lm -lrt -ldl -lasound -ljack -ldrm -lgbm -lgnutls -lnettle -lhogweed -lgmp -lidn2 -lunistring -lp11-kit -lxml2 -lfdk-aac -lmp3lame -lFLAC -lopus -lass -lsoxr' \
--disable-everything \
--enable-shared --disable-static --disable-debug --enable-stripping --enable-lto --enable-pic --enable-gpl --enable-version3 --enable-nonfree \
--enable-pthreads --enable-network --enable-asm --enable-inline-asm --enable-neon --enable-runtime-cpudetect \
--enable-avcodec --enable-avformat --enable-avfilter --enable-swresample --enable-swscale --enable-avdevice --enable-postproc \
--enable-libxml2 --enable-libdrm --enable-libudev --enable-libass --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libfreetype --enable-libharfbuzz --enable-libfribidi \
--enable-libjack --enable-alsa --enable-libplacebo --enable-libshaderc --enable-vulkan --enable-opengl --enable-epoxy --enable-ladspa --enable-lv2 --enable-librubberband --enable-gnutls --enable-gcrypt \
--enable-v4l2-m2m --enable-v4l2-request --enable-hwaccel=hevc_v4l2request \
--enable-indev=jack --enable-indev='v4l2,alsa,fbdev,kmsgrab,lavfi' \
--enable-outdev='v4l2,alsa,fbdev,drm,kmsgrab' \
--enable-demuxer='matroska,mpegts,mov,flac,wav,mp3,ogg,aac,avi,h264,hevc,rtsp,sdp,rtp,rtmp,hls,dash,mjpeg,image2,concat,rawvideo,caf,aiff' \
--enable-muxer='matroska,mp4,mov,avi,flac,wav,mp3,opus,ogg,rtp,rtmp,rtsp,hls,dash,mpegts,adts,image2,rawvideo,null,caf,aiff' \
--enable-decoder='h264,hevc,mpeg1video,mpeg2video,mpeg4,mjpeg,h263,h263p,h264_v4l2m2m,hevc_v4l2m2m,mpeg1_v4l2m2m,mpeg2_v4l2m2m,mpeg4_v4l2m2m,h263_v4l2m2m,vc1_v4l2m2m,vp8_v4l2m2m,vp9_v4l2m2m,hevc_v4l2request,opus,aac,ac3,eac3,mp3,mpegaudio,flac,vorbis,ass,srt,pcm_s16le,pcm_s24le,mov_text,dvdsub,dvbsub,rawvideo' \
--enable-encoder='h264_v4l2m2m,hevc_v4l2m2m,mpeg1_v4l2m2m,mpeg2_v4l2m2m,mpeg4_v4l2m2m,mjpeg_v4l2m2m,h263_v4l2m2m,vp8_v4l2m2m,libfdk_aac,libmp3lame,libopus,flac,ass,srt,pcm_s16le,pcm_s24le,mov_text,rawvideo' \
--enable-protocol='pipe,file,fd,tcp,udp,rtp,rtsp,http,https,tls,rtmp,rtmpt,rtmpe,rtmps,ffrtmpcrypt,hls,dash,srt,unix,cache,crypto,concat' \
--enable-filter='hwupload,hwdownload,hwmap,format,scale,vulkan,libplacebo,scale_v4l2m2m,deinterlace_v4l2m2m,fps,setdar,settb,setpts,asettb,asetpts,concat,aresample,aformat,volume,loudnorm,equalizer,bass,treble,crystalizer,ladspa,lv2,rubberband,afifo,anull,asplit,amix,anequalizer,surround,stereowiden,overlay,drawtext,pad,pan,yadif,nullsrc' \
--enable-parser='h264,hevc,mjpeg,mpegvideo,mpeg4video,mp3,mpegaudio,aac,opus,flac,vorbis,h263' \
--enable-bsf='h264_mp4toannexb,hevc_mp4toannexb,mpeg4_unpack_bframes,aac_adtstoasc,opus_metadata,extract_extradata,null' \
--enable-xlib \
--disable-libpulse --disable-indev=pulse --disable-outdev=pulse \
--disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages \
--disable-sdl2 --disable-sndio --disable-amf --disable-vdpau --disable-vaapi --disable-cuda-llvm --disable-cuvid --disable-nvenc --disable-nvdec --disable-libnpp --disable-cuda --disable-cuda-nvcc --disable-omx --disable-omx-rpi --disable-mmal \
--enable-filter=libplacebo

#!/bin/bash

PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/local/lib/aarch64-linux-gnu/pkgconfig" \
./configure --prefix=/usr \
--libdir=/usr/lib/aarch64-linux-gnu \
--incdir=/usr/include/aarch64-linux-gnu \
--extra-version=ultra-pi5-c \
--arch=aarch64 --target-os=linux --cpu=cortex-a76 \
--extra-cflags='-I/usr/include/libdrm -I/usr/include/gbm -mcpu=cortex-a76+crypto -O2 -pipe -ftree-vectorize -flto -Wno-stringop-overflow -I/usr/include/vulkan' \
--extra-ldflags='-L/usr/lib/aarch64-linux-gnu -Wl,-O1 -Wl,-rpath,/usr/lib/aarch64-linux-gnu -Wl,--as-needed -flto -lstdc++' \
--extra-libs='-lpthread -lm -lrt -ldl -lasound -ljack -ldrm -lgbm -lgnutls -lnettle -lhogweed -lgmp -lidn2 -lunistring -lp11-kit -lxml2 -lfdk-aac -lmp3lame -lFLAC -lopus -lass -lsoxr' \
--disable-everything \
--enable-shared --disable-static --disable-debug --enable-stripping --enable-lto --enable-pic --enable-gpl --enable-version3 --enable-nonfree \
--enable-pthreads --enable-network --enable-asm --enable-inline-asm --enable-neon --enable-runtime-cpudetect \
--enable-avcodec --enable-avformat --enable-avfilter --enable-swresample --enable-swscale --enable-avdevice --enable-postproc \
--enable-libxml2 --enable-libdrm --enable-libudev --enable-libass --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libfreetype --enable-libharfbuzz --enable-libfribidi \
--enable-libjack --enable-alsa --enable-libplacebo --enable-libshaderc --enable-vulkan --enable-opengl --enable-epoxy --enable-ladspa --enable-lv2 --enable-librubberband --enable-gnutls --enable-gcrypt \
--enable-v4l2-m2m --enable-v4l2-request --enable-hwaccel=hevc_v4l2request \
--enable-indev=jack --enable-indev='v4l2,alsa,fbdev,kmsgrab,lavfi' \
--enable-outdev='v4l2,alsa,fbdev,drm,kmsgrab' \
--enable-demuxer='matroska,mpegts,mov,flac,wav,mp3,ogg,aac,avi,h264,hevc,rtsp,sdp,rtp,rtmp,hls,dash,mjpeg,image2,concat,rawvideo,caf,aiff' \
--enable-muxer='matroska,mp4,mov,avi,flac,wav,mp3,opus,ogg,rtp,rtmp,rtsp,hls,dash,mpegts,adts,image2,rawvideo,null,caf,aiff' \
--enable-decoder='h264,hevc,mpeg1video,mpeg2video,mpeg4,mjpeg,h263,h263p,h264_v4l2m2m,hevc_v4l2m2m,mpeg1_v4l2m2m,mpeg2_v4l2m2m,mpeg4_v4l2m2m,h263_v4l2m2m,vc1_v4l2m2m,vp8_v4l2m2m,vp9_v4l2m2m,hevc_v4l2request,opus,aac,ac3,eac3,mp3,mpegaudio,flac,vorbis,ass,srt,pcm_s16le,pcm_s24le,mov_text,dvdsub,dvbsub,rawvideo' \
--enable-encoder='h264_v4l2m2m,hevc_v4l2m2m,mpeg1_v4l2m2m,mpeg2_v4l2m2m,mpeg4_v4l2m2m,mjpeg_v4l2m2m,h263_v4l2m2m,vp8_v4l2m2m,libfdk_aac,libmp3lame,libopus,flac,ass,srt,pcm_s16le,pcm_s24le,mov_text,rawvideo' \
--enable-protocol='pipe,file,fd,tcp,udp,rtp,rtsp,http,https,tls,rtmp,rtmpt,rtmpe,rtmps,ffrtmpcrypt,hls,dash,srt,unix,cache,crypto,concat' \
--enable-filter='hwupload,hwdownload,hwmap,format,scale,vulkan,libplacebo,scale_v4l2m2m,deinterlace_v4l2m2m,fps,setdar,settb,setpts,asettb,asetpts,concat,aresample,aformat,volume,loudnorm,equalizer,bass,treble,crystalizer,ladspa,lv2,rubberband,afifo,anull,asplit,amix,anequalizer,surround,stereowiden,overlay,drawtext,pad,pan,yadif,nullsrc' \
--enable-parser='h264,hevc,mjpeg,mpegvideo,mpeg4video,mp3,mpegaudio,aac,opus,flac,vorbis,h263' \
--enable-bsf='h264_mp4toannexb,hevc_mp4toannexb,mpeg4_unpack_bframes,aac_adtstoasc,opus_metadata,extract_extradata,null' \
--enable-xlib \
--disable-libpulse --disable-indev=pulse --disable-outdev=pulse \
--disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages \
--disable-sdl2 --disable-sndio --disable-amf --disable-vdpau --disable-vaapi --disable-cuda-llvm --disable-cuvid --disable-nvenc --disable-nvdec --disable-libnpp --disable-cuda --disable-cuda-nvcc --disable-omx --disable-omx-rpi --disable-mmal \
--enable-filter=libplacebo


