context.modules = [

    { name = libpipewire-module-rt
        args = {
            nice.level   = -19
            rt.prio      = 95
            # rt.time.soft = -1
            # rt.time.hard = -1
        }
        flags = [ ifexists nofail ]
    }

    # Weitere Standardmodule folgen hier drunter...
]
