stream.rules = [
    {
        matches = [
            {
                node.name = "~.*"
            }
        ]
        actions = {
            update-props = {
                resample.quality = 20
		resample.method   = "soxr"
            }
        }
    }
]
