context.properties = {
    default.clock.rate          = 48000
    default.clock.quantum       = 256
    default.clock.min-quantum   = 256
    default.clock.max-quantum   = 256
    default.clock.allowed-rates = [ 44100 48000 88200 96000 192000 ]
    mem.allow-mlock             = true
}

# Dies zwingt alle neuen Streams (inkl. rpicam-vid) auf S32LE
stream.properties = {
    audio.format = "F32LE"
    resample.quality = 4
}


context.modules = [
    { name = libpipewire-module-rt
        args = {
            nice.level = -15
            rt.prio = 95
            rt.time.soft = 200000
            rt.time.hard = 200000
            uclimit      = true
        }
    }
]
