context.properties = {
    default.clock.rate          = 48000
    default.clock.quantum       = 256
    default.clock.min-quantum   = 256
    default.clock.max-quantum   = 256
    default.clock.allowed-rates = [ 44100 48000 88200 96000 192000 ]
    mem.allow-mlock             = true
    resample.quality            = 20
    resample.method             = "soxr"
    settings.check-quantum      = true
    settings.check-rate         = true
}

context.modules = [
    # 1. Das Echtzeit-Modul für niedrige Latenzen
    { name = libpipewire-module-rt
      args = {
          nice.level   = -15
          rt.prio      = 95
          rt.time.soft = 200000
          rt.time.hard = 200000
          uclimit      = true
      }
    }

    # 2. Das PulseAudio-Protokoll für Ihre Anwendungen
    { name = libpipewire-module-protocol-pulse
      args = {
          pulse.properties = {
              pulse.min.quantum = 256/48000
              resample.quality  = 20
              resample.method   = "soxr"
          }
      }
    }
]

