monitor.alsa.rules = [
  {
    # 1. Steinberg UR22C Eingänge komplett ausblenden
    matches = [
      { node.name = "~alsa_input.usb-Yamaha*" }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  },
  { 
    # 2. Unitek Y-247A (C-Media) als primäres Mono-Mikrofon erzwingen
    matches = [
      { node.name = "~alsa_input.usb-0d8c_USB_Audio_Device-00.*" }
    ]
    actions = {
      update-props = {
        node.priority    = 2500
        node.description = "Hauptmikrofon (Unitek Mono)"
        audio.format     = "S32LE"
      }
    }
  },
  {
    # 4. Globale Resample-Qualität (Gilt für jeden ALSA-Audioknoten)
    # HINWEIS: Spezifische Audioformate aus vorherigen Regeln können hierdurch überschrieben werden.
    matches = [
      { node.name = "~.*" }
    ]
    actions = {
      update-props = {
        resample.quality = 20 
        resample.method   = "soxr"
        audio.format     = "S32LE"
      }
    }
  }
]
